### ISSUE TITLE
Python 3.10. Builtin and extension functions that take integer arguments no longer accept Decimals, Fractions and other objects that can be converted to integers only with a loss

### ISSUE THREAD

**Issue by ddund** [SamSchott/maestral-qt#18]
Original issue here. https://github.com/SamSchott/maestral/issues/509#issue-1043299490

From the python 3.10 changelog:

> [bpo-37999](https://bugs.python.org/issue37999): Builtin and extension functions that take integer arguments no longer accept Decimals, Fractions and other objects that can be converted to integers only with a loss (e.g. that have the __int__() method but do not have the __index__() method).

I think this is the problematic line:
https://github.com/SamSchott/maestral-qt/blob/853eb8d32ec3740c1ddfae4fbbbae9ab03e81459/maestral_qt/setup_dialog.py#L70

changing it to

```
width = self.pushButtonAuthPageCancel.width() * 1.1
width = int(width)
```

made it work for me. I'm not sure if this is the appropriate fix or if there should be some version check that we're above 3.10 before converting to an integer. Let me know what you think and I'll be happy to make a PR.

**Comment by ddund** [comment]
Okay, so I was wrong that only changing that line fixed the issue. After setting Maestral up I am unable to launch the gui. I guess there are more functions that needs to be handled.

```
$ maestral gui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 186, in set_profile_pic_from_cache
    pixmap = get_masked_image(
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/utils.py", line 181, in get_masked_image
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.cache/maestral/maestral_profile_pic.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/maestral/cli.py", line 711, in gui
    run(config_name)
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/main.py", line 631, in run
    maestral_gui.load_maestral()
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/main.py", line 197, in load_maestral
    self.setup_ui_linked()
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/main.py", line 254, in setup_ui_linked
    self.settings_window = SettingsWindow(self, self.mdbx)
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 117, in __init__
    self.refresh_gui()
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 153, in refresh_gui
    self.set_profile_pic_from_cache()
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 190, in set_profile_pic_from_cache
    pixmap = get_masked_image(FACEHOLDER_PATH, size=self._profile_pic_height)
  File "/usr/local/lib/python3.10/site-packages/maestral_qt/utils.py", line 192, in get_masked_image
    rect = QRect(
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
```

**Comment by SamSchott** [comment]
Yes, your approach of converting `float` to `int` is probably the best (only?) solution.

Unlike the Cocoa GUI, the Qt GUI hasn't yet adopted type annotations and type checking with mypy. This is partially because the user interface is mostly defined in `.ui` files instead of Python code. That makes finding the offending cases a bit more cumbersome...

**Comment by raffaem** [comment]
> Yes, your approach of converting `float` to `int` is probably the best (only?) solution.
> 
> Unlike the Cocoa GUI, the Qt GUI hasn't yet adopted type annotations and type checking with mypy. This is partially because the user interface is mostly defined in `.ui` files instead of Python code. That makes finding the offending cases a bit more cumbersome...

The log posted by @ddund shows:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/.cache/maestral/maestral_profile_pic.jpeg'
```

I don't think that's due to type conversions

**Comment by raffaem** [comment]
Fixed

**Comment by SamSchott** [comment]
@raffaem, the `FileNotFoundError` will always occur for users who don't have a custom profile picture set for their account. It is typically caught and handled by falling back to a placeholder image. However, this fallback code now also fails. Therefore the line:

```
During handling of the above exception, another exception occurred:
```

**Comment by raffaem** [comment]
> @raffaem, the `FileNotFoundError` will always occur for users who don't have a custom profile picture set for their account. It is typically caught and handled by falling back to a placeholder image. However, this fallback code now also fails. Therefore the line:
> 
> ```
> During handling of the above exception, another exception occurred:
> ```

Thanks :) Is my PR up for review?
