### ISSUE TITLE
maestral-qt 1.8.0.dev0 does not start

### ISSUE THREAD

**Issue by ceamac** [samschott/maestral-qt#26]
Hi,

```
$ maestral gui
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/maestral", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/maestral/cli/cli_core.py", line 306, in gui
    run = entry_point.load()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/maestral_qt/main.py", line 45, in <module>
    from .setup_dialog import SetupDialog
  File "/usr/lib/python3.11/site-packages/maestral_qt/setup_dialog.py", line 16, in <module>
    from .utils import MaestralBackgroundTask, icon_to_pixmap, is_empty
  File "/usr/lib/python3.11/site-packages/maestral_qt/utils.py", line 21, in <module>
    from .resources import rgb_to_luminance
  File "/usr/lib/python3.11/site-packages/maestral_qt/resources/__init__.py", line 24, in <module>
    APP_ICON_PATH = resource_path("maestral.png")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: resource_path() missing 1 required positional argument: 'resource'
```

I think it is because you have a declaration with 2 parameters above:
```
def resource_path(package: str, resource: str):
```

**Comment by samschott** [comment]
Thanks for catching this early!
